services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      # Mock media mount for dev
      - ./media_example:/media
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
      - "80:80" # Maps the server port if running server locally inside dev container